apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  - title: Fill in some steps
    properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the component
        system:
          title: System
          type: string
          description: System for the service
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System
  steps:
    - id: setupAuthentication
      action: auth:create
      input:
        # make sure to use ${{ secrets.parameterName }} to reference these values
        username: ${{ firstName }}
        password: ${{ lastName }}
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  # steps:
  #   # Each step executes an action, in this case one templates files into the working directory.
  #   - id: fetch-base
  #     name: Fetch Base
  #     action: fetch:template
  #     input:
  #       url: ./content
  #       values:
  #         name: ${{ parameters.name }}

    # # This step publishes the contents of the working directory to GitHub.
    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}

    # # The final step is to register our new component in the catalog.
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}


---

apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: s3-bucket-on-ocean
  title: Create S3 bucket on Ocean Cloud
  description: An example of Ocean integration
  tags: 
    - ocean
spec:
  owner: user:guest
  type: resource

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  - title: Fill in some steps
    properties:
        name:
          title: Bucket name
          type: string
          description: Unique name of the S3 bucket
        description:
          title: Description
          type: string
          description: A description for the component
  steps:
    - id: setupAuthentication
      action: auth:create
      input:
        # make sure to use ${{ secrets.parameterName }} to reference these values
        username: ${{ firstName }}
        password: ${{ lastName }}
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  # steps:
  #   # Each step executes an action, in this case one templates files into the working directory.
  #   - id: fetch-base
  #     name: Fetch Base
  #     action: fetch:template
  #     input:
  #       url: ./content
  #       values:
  #         name: ${{ parameters.name }}

    # # This step publishes the contents of the working directory to GitHub.
    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}

    # # The final step is to register our new component in the catalog.
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

---

apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: team-project
  title: Create new Project in Product Factory
  description: An example of integration with Product Factory
  tags: 
    - pf
spec:
  owner: user:guest
  type: tools

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  - title: Fill in some steps
    properties:
        name:
          title: Project name
          type: string
          description: Unique name of the Project
        description:
          title: Description
          type: string
          description: A description for the component
  steps:
    - id: setupAuthentication
      action: auth:create
      input:
        # make sure to use ${{ secrets.parameterName }} to reference these values
        username: ${{ firstName }}
        password: ${{ lastName }}
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  # steps:
  #   # Each step executes an action, in this case one templates files into the working directory.
  #   - id: fetch-base
  #     name: Fetch Base
  #     action: fetch:template
  #     input:
  #       url: ./content
  #       values:
  #         name: ${{ parameters.name }}

    # # This step publishes the contents of the working directory to GitHub.
    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}

    # # The final step is to register our new component in the catalog.
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

---
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: product-onboarding
  title: Onboard new Product on the platform
  description: This wizard helps to onboard new product on the platform
spec:
  owner: user:guest
  type: product

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  - title: Fill in some details
    properties:
        name:
          title: Код продукта
          type: string
          description: Код продукта PPInfo
          # ui:field: EntityNamePicker
          # ui:autofocus: true
        description:
          title: Описание продукта
          type: string
          description: Краткое описание
        system:
          title: Владелец
          type: string
          description: Команда продукта
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Group
            defaultKind: Group
  steps:
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ name }}
        catalogInfoPath: '/import-product.yaml'