apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ocean
  title: Ocean
  tags:
    - platform
    - core
spec:
  owner: ocean-core
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vm-1
  title: Virtual Machine (VM1)
  tags:
    - vm
spec:
  owner: the-platform-core
  type: vm
  system: the-platform
  partOf: ocean
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vm-2
  title: Virtual Machine (VM2)
  tags:
    - vm
spec:
  owner: the-platform-core
  type: vm
  system: the-platform
  partOf: ocean
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-service
  annotations:
    prometheus.io/rule: last_over_time(intpl_api_subscriptions_total[30m])
  description: 'Тестовый сервис'
spec:
  type: service
  owner: group:the-platform-core
  lifecycle: production
  profile:
    displayName: "Тестовый сервис"
  system: the-platform

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: db-1
  title: PostgreSQL (DB)
  tags:
    - db
spec:
  owner: the-platform-core
  type: db
  system: the-platform
  partOf: ocean
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cluster-1
  title: Kubernetes Cluster(k8s)
  tags:
    - db
spec:
  owner: the-platform-core
  type: k8s
  system: the-platform
  partOf: ocean
