# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ep
  title: EP Product Catalog
  annotations:
      backstage.io/techdocs-ref: dir:.
      mts.ru/ppinfo: code:123
      mts.ru/sol: id:123
  links:
    - url: https://confluence.mts.ru/pages/viewpage.action?pageId=378648201
      title: Confluence Space
      icon: dashboard
      type: kb-space
  tags:
    - platform
    - ecommerce
spec:
  owner: EP_ProductCatalogue_Team
  domain: biz-platforms
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: example-website
# spec:
#   type: website
#   lifecycle: experimental
#   owner: guests
#   system: ep
#   providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: EP_ProductCatalogue_Team
  system: ep
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SBS.453
  title: SBS.453 - Управление прайс-листом
  annotations:
     backstage.io/techdocs-entity: system:default/ep
     backstage.io/techdocs-ref: dir:./overview/services/
spec:
  type: service
  lifecycle: experimental
  owner: EP_ProductCatalogue_Team
  system: ep


---
apiVersion: mts.ru/v1alpha1
kind: Product
metadata:
  name: test-product
  title: My Product
  description: |
    Capability Product Catalog в Enablement Platform - создание спецификаций 
    с базовыми характеристиками продукта для дальнейшей, персонализации, продажи и обслуживания на ЕР  
  annotations:
    mts.ru/ppinfo: id:BI_2844
    mts.ru/oracle: code:ENPL
  links:
    - url: https://confluence.mts.ru/pages/viewpage.action?pageId=378648201
      title: Confluence
      icon: dashboard
spec:
  type: internal
  lifecycle: experimental 
  owner: biz-platforms-team

---
apiVersion: mts.ru/v1alpha1
kind: Product
metadata:
  name: test-product-2
  title: My Product 2
  description: |
    Capability Product Catalog в Enablement Platform - создание спецификаций 
    с базовыми характеристиками продукта для дальнейшей, персонализации, продажи и обслуживания на ЕР  
  annotations:
    mts.ru/ppinfo: id:BI_2844
    mts.ru/oracle: code:ENPL
  links:
    - url: https://confluence.mts.ru/pages/viewpage.action?pageId=378648201
      title: Confluence
      icon: dashboard
spec:
  type: internal
  lifecycle: experimental
  owner: EP_ProductCatalogue_Team

# ---

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: a-unique-name-for-your-docs
#   annotations:
#     # this could also be `url:<url>` if the documentation isn't in the same location
#     backstage.io/techdocs-ref: dir:.
# spec:
#   type: documentation
#   lifecycle: experimental
#   owner: EP_ProductCatalogue_Team

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: App1
#   annotations:
#     mts.ru/ppinfo-ref: code:123
#     mts.ru/sol-ref: code:SBS.453
# spec:
#   type: application
#   lifecycle: experimental
#   owner: EP_ProductCatalogue_Team
#   system: ep
