# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dktabolich
spec:
  memberOf: [the-platform-core]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: biz-platforms-team
  title: ИТ-кластер "Бизнес платформы"
spec:
  type: it-cluster
  displayName: ИТ-кластер "Бизнес платформы"
  email: biz-platforms-team@mts.ru
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: the-platform-core
  title: The Platform Core
spec:
  type: team
  displayName: The Platform Core Team
  email: the-platform-core@mts.ru
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ocean-core
  title: Ocean Core Team
spec:
  type: team
  displayName: Ocean Cloud Core Team
  email: ocean-core@mts.ru
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rnd-core
  title: R&D Core Team
spec:
  type: team
  displayName: R&D Core Team
  email: rnd@mts.ru
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tech-gov
  title: TechGov
spec:
  type: team
  displayName: TechGov Team
  email: tech-gov@mts.ru
  children: [the-platform-core, rnd-core]